// Pairs with references/07_language_parser_definition_psi_file.md — the registration glue between
// lexer, parser, and PSI.
package com.example.simplelang

import com.example.simplelang.psi.SimpleTypes
import com.intellij.lang.ASTNode
import com.intellij.lang.ParserDefinition
import com.intellij.lang.PsiParser
import com.intellij.lexer.FlexAdapter
import com.intellij.lexer.Lexer
import com.intellij.openapi.project.Project
import com.intellij.psi.FileViewProvider
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import com.intellij.psi.TokenType
import com.intellij.psi.tree.IFileElementType
import com.intellij.psi.tree.TokenSet

class SimpleLexerAdapter : FlexAdapter(SimpleLexer(null))

class SimpleParserDefinition : ParserDefinition {
  override fun createLexer(project: Project): Lexer = SimpleLexerAdapter()
  override fun createParser(project: Project): PsiParser = SimpleParser()  // generated by Grammar-Kit
  override fun getFileNodeType(): IFileElementType = FILE
  override fun getCommentTokens(): TokenSet = COMMENTS
  override fun getStringLiteralElements(): TokenSet = TokenSet.EMPTY
  override fun createElement(node: ASTNode): PsiElement = SimpleTypes.Factory.createElement(node)
  override fun createFile(viewProvider: FileViewProvider): PsiFile = SimpleFile(viewProvider)

  companion object {
    val WHITE_SPACES = TokenSet.create(TokenType.WHITE_SPACE)
    val COMMENTS     = TokenSet.create(SimpleTypes.COMMENT)
    val FILE         = IFileElementType(SimpleLanguage)
  }
}
